# Generated by Django 4.1 on 2022-10-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_persor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persor',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='primeiro nome'),
        ),
        migrations.AlterField(
            model_name='persor',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='segundo nome'),
        ),
        migrations.AlterField(
            model_name='persor',
            name='telefone',
            field=models.CharField(max_length=19, null=True, verbose_name='telefone'),
        ),
    ]
